### ISSUE TITLE
请问这个版本 支持nginx 作为客户端的时候 可以和后端服务器自适应TLS和 GMTLS嘛

### ISSUE THREAD

**Issue by ffashion** [jntass/TASSL-1.1.1k#1]

**Comment by jntass** [comment]
不支持，服务端可以自适应是因为可以根据client hello中的版本号选择协议。但是客户端不可以，客户端开始发client hello的时候必须确定自己使用的协议是国密SSL或是其它的比如TLS1.2。客户端可以通过尝试不同的协议是否成功来自适应，这也是大多数浏览器的做法

**Comment by ffashion** [comment]
那有没有计划 修改一下nginx 代码 比如发2次包 第一次GMTLS  第二次TLS

**Comment by jntass** [comment]
暂时没有，这种定制改动比较大
