### ISSUE TITLE
有联系方式么，按照你们的文档编译总是不成功

### ISSUE THREAD

**Issue by ujshenry** [jntass/TASSL-1.1.1k#2]
有联系方式么，按照你们的文档编译总是不成功

**Comment by ujshenry** [comment]
安装nginx时，使用还是使用的自带的openssl模块编译的，而不是使用tassl

**Comment by jntass** [comment]
应该是由于系统有自带的ssl库，nginx构建的时候依赖了系统的ssl库。

更新了文档，tassl和nginx使用静态库的配置方式

**Comment by ujshenry** [comment]
> 应该是由于系统有自带的ssl库，nginx构建的时候依赖了系统的ssl库。
> 
> 更新了文档，tassl和nginx使用静态库的配置方式

好的 谢谢
