### ISSUE TITLE
{E0,11} ECDHE-SM4-SM3 套件下，服务端实现是否需要显式指定客户端证书校验

### ISSUE THREAD

**Issue by dramenk** [jntass/TASSL-1.1.1k#28]
发现在 E011 套件下，服务端必须要**显式指定客户端证书校验**才能够正常握手：

`
openssl s_server -accept 443 -cert certs/SS.pem -key certs/SS.key -cert_enc certs/SE.pem -key_enc certs/SE.key -verify 1
openssl s_client -connect 127.0.0.1:443 -gmtls1_1 -cert certs/CS.pem -key certs/CS.key -cert_enc certs/CE.pem -key_enc certs/CE.key -cipher ECDHE-SM4-SM3
`

否则报错：

`ERROR
verify error:unable to verify the first certificate
140507031963456:error:14180044:SSL routines:tls_post_process_client_key_exchange:internal error:ssl/statem/statem_srvr.c:3885:`

看代码实现，当协商出 E011 套件之后，服务端应该会自动对客户端证书发出校验请求，不需要显式指定。

可否帮忙确认这里的策略目前是怎么样的？

或者是否 bug，因为这里的逻辑似乎与 TASSL-1.1.1b 有些差异：
https://github.com/jntass/TASSL-1.1.1k/blob/master/ssl/statem/statem_srvr.c#L2513
https://github.com/jntass/TASSL-1.1.1b/blob/V_1.4/ssl/statem/statem_srvr.c#L2469

@jntass

**Comment by yanshichao0226** [comment]
> 发现在 E011 套件下，服务端必须要显式指定客户端证书校验才能够正常握手

ECDHE-SM4-SM3套件客户端需要拥有证书才能完成握手；服务端需要发送证书请求，当前版本需显式调用接口SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER|SSL_VERIFY_FAIL_IF_NO_PEER_CERT, NULL)
