### ISSUE TITLE
RFC 8998单证书是怎么体现的

### ISSUE THREAD

**Issue by Dave379776966** [jntass/TASSL-1.1.1k#7]
你好，看了你们的PDF文档。有些模糊，能详细说说单证书这块是怎么体现的吗？

**Comment by yanshichao0226** [comment]
RFC 8998套件测试：
服务端：./openssl s_server -cert ../tassl_demo/cert/certs/SS.crt -key ../tassl_demo/cert/certs/SS.key -Verify 10 -CAfile ../tassl_demo/cert/certs/CA.crt -accept 4433
客户端：./openssl s_client -connect 127.0.0.1:4433 -tls1_3 -ciphersuites TLS_SM4_GCM_SM3 -cert ../tassl_demo/cert/certs/CS.crt -key ../tassl_demo/cert/certs/CS.key -verify 10 -CAfile ../tassl_demo/cert/certs/CA.crt

大概流程就是在TLS1.3协议中增加了TLS_SM4_GCM_SM3/TLS_SM4_CCM_SM3两个套件，同时使用SM2证书进行身份验证且只用做身份验证（区别于国密SSL中签名证书用作身份验证，加密证书用作密钥交换；因为使用证书中的密钥进行会话密钥交换非前向安全，TLS1.3协议不再使用非前向安全套件），密钥交换算法沿用TLS1.3的标准(EC)DHE。

**Comment by zzl360** [comment]
#20

**Comment by Dave379776966** [comment]
> RFC 8998套件测试： 服务端：./openssl s_server -cert ../tassl_demo/cert/certs/SS.crt -key ../tassl_demo/cert/certs/SS.key -Verify 10 -CAfile ../tassl_demo/cert/certs/CA.crt -accept 4433 客户端：./openssl s_client -connect 127.0.0.1:4433 -tls1_3 -ciphersuites TLS_SM4_GCM_SM3 -cert ../tassl_demo/cert/certs/CS.crt -key ../tassl_demo/cert/certs/CS.key -verify 10 -CAfile ../tassl_demo/cert/certs/CA.crt
> 
> 大概流程就是在TLS1.3协议中增加了TLS_SM4_GCM_SM3/TLS_SM4_CCM_SM3两个套件，同时使用SM2证书进行身份验证且只用做身份验证（区别于国密SSL中签名证书用作身份验证，加密证书用作密钥交换；因为使用证书中的密钥进行会话密钥交换非前向安全，TLS1.3协议不再使用非前向安全套件），密钥交换算法沿用TLS1.3的标准(EC)DHE。



如果私钥放在了UsbKey里，服务器和客户端怎么认证呢？求解
@yanshichao0226

**Comment by zzl360** [comment]
> > RFC 8998套件测试： 服务端：./openssl s_server -cert ../tassl_demo/cert/certs/SS.crt -key ../tassl_demo/cert/certs/SS.key -Verify 10 -CAfile ../tassl_demo/cert/certs/CA.crt -accept 4433 客户端：./openssl s_client -connect 127.0.0.1:4433 -tls1_3 -ciphersuites TLS_SM4_GCM_SM3 -cert ../tassl_demo/cert/certs/CS.crt -key ../tassl_demo/cert/certs/CS.key -verify 10 -CAfile ../tassl_demo/cert/certs/CA.crt
> > 大概流程就是在TLS1.3协议中增加了TLS_SM4_GCM_SM3/TLS_SM4_CCM_SM3两个套件，同时使用SM2证书进行身份验证且只用做身份验证（区别于国密SSL中签名证书用作身份验证，加密证书用作密钥交换；因为使用证书中的密钥进行会话密钥交换非前向安全，TLS1.3协议不再使用非前向安全套件），密钥交换算法沿用TLS1.3的标准(EC)DHE。
> 
> 如果私钥放在了UsbKey里，服务器和客户端怎么认证呢？求解 @yanshichao0226

rfc8998没有定义双向认证的情况，当然可以参考tls1.3实现国密算法套件的双向认证，无非就是调用skf接口对数据进行签名和验签。8998里不涉及调用skf进行公钥加密、私钥解密（skf未定义这个接口）。
